# https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops
# which branch to trigger on * means any
trigger:
- '*'

# set some vars to use later
variables:
  buildConfiguration: 'Release'
  
# set the stages of the pipeline
# multistage pipeline enables you to define distinct phases that your change passes through as it's promoted through the pipeline
# Each stage defines the agent, variable, and steps required to carry out that phase of the pipeline
#  Stages break down into jobs, which are a series of steps & tasks that run sequentially as a unit

# build stage
stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    # set the agent pool
    pool:
      vmImage: 'ubuntu-18.04'
      demands:
      - npm
    # stage variables
    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '3.1.300'
    # use .net core dependencies
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'
    # install node package manager
    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false
    # custom script to compile sass
    - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
      displayName: 'Compile Sass assets'
    # run gulp   
    - task: gulp@1
      displayName: 'Run gulp tasks'
    # write build info to text file
    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: $(wwwrootDir)
    # restore dependencies
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
    # build the code into dlls
    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'
    # publish the code
    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true
   # publish the artifact to the pipeline folder
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

# deploy stage
- stage: 'Deploy'
  displayName: 'Deploy the web application'
  # will only execute after build stage completed
  dependsOn: Build
  # define the jobs
  jobs:
  - deployment: Deploy
    # set the agent pool
    pool:
      vmImage: 'ubuntu-18.04'
    environment: dev
    # deployment vars
    variables:
    - group: Release
    # set execution strategy to run only once
    strategy:
      runOnce:
        # deploy hook
        deploy:
          steps:
          # current pipeline and artifact to deploy
          - download: current
            artifact: drop
          # built in task for App Service deploys
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              appType: 'webAppLinux'
              # name of the service connection
              azureSubscription: 'Resource Manager - Tailspin - Space Game'
              # reads the web app name from your pipeline variable
              appName: '$(WebAppName)'
              # get the zip to deploy
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'